[package]
name = "learn_13_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 导入 learn_library_1 库
learn_library_1 = { path = "./learn_library_1" }
